/**
 * Wood Grain Background — Interactive particle flow field
 *
 * Particles flow along organic curves generated by layered simplex noise,
 * creating patterns reminiscent of wood grain. Mouse/touch interaction
 * distorts the field, pushing particles into beautiful swirls.
 *
 * Theme-aware: uses warm wood tones for dark mode, golden honey tones for light.
 */

// ─── Simplex Noise (compact 2D implementation) ───────────────────────────────

const F2 = 0.5 * (Math.sqrt(3) - 1);
const G2 = (3 - Math.sqrt(3)) / 6;
const grad2 = [
  [1, 1], [-1, 1], [1, -1], [-1, -1],
  [1, 0], [-1, 0], [0, 1], [0, -1],
];

let perm: Uint8Array;
let permMod8: Uint8Array;

function seedNoise(seed: number) {
  const p = new Uint8Array(256);
  for (let i = 0; i < 256; i++) p[i] = i;
  // Fisher-Yates shuffle with seed
  let s = seed;
  for (let i = 255; i > 0; i--) {
    s = (s * 16807 + 0) % 2147483647;
    const j = s % (i + 1);
    [p[i], p[j]] = [p[j], p[i]];
  }
  perm = new Uint8Array(512);
  permMod8 = new Uint8Array(512);
  for (let i = 0; i < 512; i++) {
    perm[i] = p[i & 255];
    permMod8[i] = perm[i] % 8;
  }
}

function simplex2(x: number, y: number): number {
  const s = (x + y) * F2;
  const i = Math.floor(x + s);
  const j = Math.floor(y + s);
  const t = (i + j) * G2;
  const X0 = i - t;
  const Y0 = j - t;
  const x0 = x - X0;
  const y0 = y - Y0;
  const i1 = x0 > y0 ? 1 : 0;
  const j1 = x0 > y0 ? 0 : 1;
  const x1 = x0 - i1 + G2;
  const y1 = y0 - j1 + G2;
  const x2 = x0 - 1 + 2 * G2;
  const y2 = y0 - 1 + 2 * G2;
  const ii = i & 255;
  const jj = j & 255;

  let n0 = 0, n1 = 0, n2 = 0;
  let t0 = 0.5 - x0 * x0 - y0 * y0;
  if (t0 >= 0) {
    const gi0 = permMod8[ii + perm[jj]];
    t0 *= t0;
    n0 = t0 * t0 * (grad2[gi0][0] * x0 + grad2[gi0][1] * y0);
  }
  let t1 = 0.5 - x1 * x1 - y1 * y1;
  if (t1 >= 0) {
    const gi1 = permMod8[ii + i1 + perm[jj + j1]];
    t1 *= t1;
    n1 = t1 * t1 * (grad2[gi1][0] * x1 + grad2[gi1][1] * y1);
  }
  let t2 = 0.5 - x2 * x2 - y2 * y2;
  if (t2 >= 0) {
    const gi2 = permMod8[ii + 1 + perm[jj + 1]];
    t2 *= t2;
    n2 = t2 * t2 * (grad2[gi2][0] * x2 + grad2[gi2][1] * y2);
  }
  return 70 * (n0 + n1 + n2);
}

// ─── Color Palettes ──────────────────────────────────────────────────────────

interface ColorSet {
  particles: [number, number, number][];  // RGB triples for manual alpha control
}

// Dark mode: rich, warm wood tones that glow against charcoal
const darkPalette: ColorSet = {
  particles: [
    [212, 165, 116],  // Lenga — honey
    [139, 94, 60],    // Algarrobo — warm brown
    [107, 45, 26],    // Quebracho — deep red-brown
    [232, 213, 183],  // Guatambú — cream
    [180, 130, 80],   // blend — amber
    [160, 100, 55],   // blend — toffee
  ],
};

// Light mode: subtle golden/sandy tones against ivory
const lightPalette: ColorSet = {
  particles: [
    [180, 140, 90],   // Lenga — muted honey
    [120, 80, 45],    // Algarrobo — soft brown
    [90, 40, 20],     // Quebracho — faded rosewood
    [200, 180, 150],  // Guatambú — warm sand
    [160, 115, 65],   // blend — wheat
    [140, 95, 50],    // blend — caramel
  ],
};

// ─── Particle ────────────────────────────────────────────────────────────────

const TRAIL_LENGTH = 120;  // max positions remembered per particle

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  rgb: [number, number, number];
  baseAlpha: number;
  size: number;
  life: number;
  maxLife: number;
  noiseOffsetX: number;
  noiseOffsetY: number;
  trail: { x: number; y: number }[];
}

// ─── Main Engine ─────────────────────────────────────────────────────────────

export function initWoodGrainBackground() {
  const canvas = document.getElementById('wood-grain-bg') as HTMLCanvasElement | null;
  if (!canvas) return;

  const ctx = canvas.getContext('2d', { alpha: false })!;
  if (!ctx) return;

  // Respect reduced motion
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reducedMotion) {
    // Draw a single static frame instead
    drawStaticGrain(canvas, ctx);
    return;
  }

  seedNoise(42);

  // ─── State ───
  let W = 0;
  let H = 0;
  let particles: Particle[] = [];
  let mouseX = -9999;
  let mouseY = -9999;
  let mouseActive = false;
  let time = 0;
  let animId = 0;
  let palette = getCurrentPalette();
  let particleCount = 0;

  // ─── Sizing ───
  function resize() {
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    W = window.innerWidth;
    H = window.innerHeight;
    canvas!.width = W * dpr;
    canvas!.height = H * dpr;
    canvas!.style.width = W + 'px';
    canvas!.style.height = H + 'px';
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    // Adapt particle count to screen size — keep it sparse and calm
    const area = W * H;
    const isMobile = W < 768;
    particleCount = isMobile
      ? Math.min(Math.floor(area / 8000), 250)
      : Math.min(Math.floor(area / 5000), 600);

    // Reset particles on resize
    initParticles();

    // Clear with current bg
    fillBackground();
  }

  function fillBackground() {
    const theme = document.documentElement.getAttribute('data-theme');
    ctx.fillStyle = theme === 'light' ? '#faf8f3' : '#1a1a18';
    ctx.fillRect(0, 0, W, H);
  }

  function getCurrentPalette(): ColorSet {
    const theme = document.documentElement.getAttribute('data-theme');
    return theme === 'light' ? lightPalette : darkPalette;
  }

  // ─── Particles ───
  function createParticle(): Particle {
    const rgb = palette.particles[Math.floor(Math.random() * palette.particles.length)];
    const maxLife = 300 + Math.random() * 500;
    const x = Math.random() * W;
    const y = Math.random() * H;
    return {
      x, y,
      vx: 0,
      vy: 0,
      rgb,
      baseAlpha: 0.35 + Math.random() * 0.25,
      size: 0.8 + Math.random() * 1.5,
      life: Math.random() * maxLife,  // stagger initial life
      maxLife,
      noiseOffsetX: Math.random() * 1000,
      noiseOffsetY: Math.random() * 1000,
      trail: [],
    };
  }

  function initParticles() {
    particles = [];
    for (let i = 0; i < particleCount; i++) {
      particles.push(createParticle());
    }
  }

  function resetParticle(p: Particle) {
    // Re-spawn at edge for continuous flow
    const edge = Math.random();
    if (edge < 0.25) {
      p.x = 0;
      p.y = Math.random() * H;
    } else if (edge < 0.5) {
      p.x = W;
      p.y = Math.random() * H;
    } else if (edge < 0.75) {
      p.x = Math.random() * W;
      p.y = 0;
    } else {
      p.x = Math.random() * W;
      p.y = H;
    }
    p.vx = 0;
    p.vy = 0;
    p.life = 0;
    p.maxLife = 300 + Math.random() * 500;
    p.rgb = palette.particles[Math.floor(Math.random() * palette.particles.length)];
    p.baseAlpha = 0.35 + Math.random() * 0.25;
    p.noiseOffsetX = Math.random() * 1000;
    p.noiseOffsetY = Math.random() * 1000;
    p.trail = [];
  }

  // ─── Flow field ───
  const NOISE_SCALE = 0.0012;
  const TIME_SCALE = 0.00003;
  const FLOW_STRENGTH = 0.5;

  function getFlowAngle(x: number, y: number, t: number): number {
    // Layered noise for organic wood grain feel
    const n1 = simplex2(x * NOISE_SCALE + t, y * NOISE_SCALE * 0.6);
    const n2 = simplex2(x * NOISE_SCALE * 2.5 + 100 + t * 0.7, y * NOISE_SCALE * 1.5 + 100);
    const n3 = simplex2(x * NOISE_SCALE * 0.5 + 200 - t * 0.3, y * NOISE_SCALE * 0.3 + 200);
    // Combine: primary flow + detail + slow drift
    return (n1 * 0.6 + n2 * 0.25 + n3 * 0.15) * Math.PI * 2;
  }

  // ─── Mouse interaction ───
  const MOUSE_RADIUS = 120;
  const MOUSE_FORCE = 1.5;

  function applyMouseForce(p: Particle) {
    if (!mouseActive) return;
    const dx = p.x - mouseX;
    const dy = p.y - mouseY;
    const distSq = dx * dx + dy * dy;
    const rSq = MOUSE_RADIUS * MOUSE_RADIUS;
    if (distSq < rSq && distSq > 1) {
      const dist = Math.sqrt(distSq);
      const force = (1 - dist / MOUSE_RADIUS) * MOUSE_FORCE;
      p.vx += (dx / dist) * force;
      p.vy += (dy / dist) * force;
    }
  }

  // ─── Animation loop ───
  function animate() {
    // Full clear each frame — no ghost trails
    fillBackground();

    time += 1;
    const t = time * TIME_SCALE;

    for (let i = 0; i < particles.length; i++) {
      const p = particles[i];
      p.life++;

      if (p.life > p.maxLife || p.x < -20 || p.x > W + 20 || p.y < -20 || p.y > H + 20) {
        resetParticle(p);
        continue;
      }

      // Store current position in trail before moving
      p.trail.push({ x: p.x, y: p.y });
      if (p.trail.length > TRAIL_LENGTH) p.trail.shift();

      // Flow field
      const angle = getFlowAngle(p.x + p.noiseOffsetX, p.y + p.noiseOffsetY, t);
      p.vx += Math.cos(angle) * FLOW_STRENGTH * 0.15;
      p.vy += Math.sin(angle) * FLOW_STRENGTH * 0.15;

      // Mouse repulsion
      applyMouseForce(p);

      // Damping — heavier friction for slower drift
      p.vx *= 0.88;
      p.vy *= 0.88;

      // Move
      p.x += p.vx;
      p.y += p.vy;

      // Fade in/out over lifetime
      const lifeRatio = p.life / p.maxLife;
      const lifeFade = lifeRatio < 0.1
        ? lifeRatio / 0.1
        : lifeRatio > 0.85
          ? (1 - lifeRatio) / 0.15
          : 1;

      const [r, g, b] = p.rgb;

      // Draw trail — sample every few points to keep draw calls manageable
      const len = p.trail.length;
      const step = len > 40 ? 4 : len > 20 ? 2 : 1;
      for (let j = 0; j < len; j += step) {
        const trailFade = (j + 1) / len;           // 0→1 from oldest to newest
        const a = p.baseAlpha * lifeFade * trailFade * 0.5;
        const sz = p.size * (0.2 + trailFade * 0.8);  // shrink toward tail
        ctx.globalAlpha = a;
        ctx.fillStyle = `rgb(${r},${g},${b})`;
        ctx.beginPath();
        ctx.arc(p.trail[j].x, p.trail[j].y, sz, 0, Math.PI * 2);
        ctx.fill();
      }

      // Draw head (current position) at full particle alpha
      ctx.globalAlpha = p.baseAlpha * lifeFade;
      ctx.fillStyle = `rgb(${r},${g},${b})`;
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
      ctx.fill();
    }

    ctx.globalAlpha = 1;
    animId = requestAnimationFrame(animate);
  }

  // ─── Event listeners ───
  function onMouseMove(e: MouseEvent) {
    mouseX = e.clientX;
    mouseY = e.clientY;
    mouseActive = true;
  }

  function onMouseLeave() {
    mouseActive = false;
  }

  function onTouchMove(e: TouchEvent) {
    const touch = e.touches[0];
    if (touch) {
      mouseX = touch.clientX;
      mouseY = touch.clientY;
      mouseActive = true;
    }
  }

  function onTouchEnd() {
    mouseActive = false;
  }

  // Listen for theme changes
  const observer = new MutationObserver(() => {
    palette = getCurrentPalette();
    // Redraw background on theme switch
    fillBackground();
  });
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ['data-theme'],
  });

  // Debounced resize
  let resizeTimer: ReturnType<typeof setTimeout>;
  function onResize() {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(resize, 150);
  }

  // ─── Init ───
  window.addEventListener('resize', onResize);
  window.addEventListener('mousemove', onMouseMove);
  document.addEventListener('mouseleave', onMouseLeave);
  window.addEventListener('touchmove', onTouchMove, { passive: true });
  window.addEventListener('touchend', onTouchEnd);

  resize();
  animate();

  // Cleanup function (not used in SPA but good practice)
  return () => {
    cancelAnimationFrame(animId);
    observer.disconnect();
    window.removeEventListener('resize', onResize);
    window.removeEventListener('mousemove', onMouseMove);
    document.removeEventListener('mouseleave', onMouseLeave);
    window.removeEventListener('touchmove', onTouchMove);
    window.removeEventListener('touchend', onTouchEnd);
  };
}

// ─── Static grain for reduced-motion users ───────────────────────────────────

function drawStaticGrain(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
  seedNoise(42);
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const W = window.innerWidth;
  const H = window.innerHeight;
  canvas.width = W * dpr;
  canvas.height = H * dpr;
  canvas.style.width = W + 'px';
  canvas.style.height = H + 'px';
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

  const theme = document.documentElement.getAttribute('data-theme');
  const pal = theme === 'light' ? lightPalette : darkPalette;

  ctx.fillStyle = theme === 'light' ? '#faf8f3' : '#1a1a18';
  ctx.fillRect(0, 0, W, H);

  // Draw static flowing lines
  const lines = Math.min(Math.floor((W * H) / 4000), 800);
  for (let i = 0; i < lines; i++) {
    let x = Math.random() * W;
    let y = Math.random() * H;
    const [r, g, b] = pal.particles[Math.floor(Math.random() * pal.particles.length)];

    ctx.strokeStyle = `rgba(${r},${g},${b},0.4)`;
    ctx.lineWidth = 0.8 + Math.random() * 1.2;
    ctx.beginPath();
    ctx.moveTo(x, y);

    for (let s = 0; s < 30; s++) {
      const angle = getStaticAngle(x, y);
      x += Math.cos(angle) * 3;
      y += Math.sin(angle) * 3;
      ctx.lineTo(x, y);
    }
    ctx.stroke();
  }
}

function getStaticAngle(x: number, y: number): number {
  const n1 = simplex2(x * 0.0015, y * 0.0009);
  const n2 = simplex2(x * 0.00375 + 100, y * 0.00225 + 100);
  return (n1 * 0.7 + n2 * 0.3) * Math.PI * 2;
}
